export default class Action {

    // SideBar Action
    static UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
    static UPDATE_CURRENT_SUBCATEGORY = 'UPDATE_CURRENT_SUBCATEGORY';
    static UPDATE_CURRENT_PRICE_RANGE = 'UPDATE_CURRENT_PRICE_RANGE';
    static UPDATE_CURRENT_PROVINCE = 'UPDATE_CURRENT_PROVINCE';
}